# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentDataset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Untitled", max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("row_count", models.IntegerField(default=0)),
                ("summary_json", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
